.PHONY: test build up down logs

test:
	cd gateway && go test ./...
	cd order && go test ./...
	cd product && go test ./...
	cd analytics && go test ./...

build:
	cd gateway && go build ./...
	cd order && go build ./...
	cd product && go build ./...
	cd analytics && go build ./...

up:
	docker compose up -d --build

down:
	docker compose down

logs:
	docker compose logs -f
