// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.36.2
// source: analytics.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRevenueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRevenueRequest) Reset() {
	*x = GetRevenueRequest{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRevenueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRevenueRequest) ProtoMessage() {}

func (x *GetRevenueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRevenueRequest.ProtoReflect.Descriptor instead.
func (*GetRevenueRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

type GetRevenueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revenue       float64                `protobuf:"fixed64,1,opt,name=revenue,proto3" json:"revenue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRevenueResponse) Reset() {
	*x = GetRevenueResponse{}
	mi := &file_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRevenueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRevenueResponse) ProtoMessage() {}

func (x *GetRevenueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRevenueResponse.ProtoReflect.Descriptor instead.
func (*GetRevenueResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *GetRevenueResponse) GetRevenue() float64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

type GetOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersRequest) Reset() {
	*x = GetOrdersRequest{}
	mi := &file_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersRequest) ProtoMessage() {}

func (x *GetOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{2}
}

type GetOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        int32                  `protobuf:"varint,1,opt,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersResponse) Reset() {
	*x = GetOrdersResponse{}
	mi := &file_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersResponse) ProtoMessage() {}

func (x *GetOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrdersResponse) GetOrders() int32 {
	if x != nil {
		return x.Orders
	}
	return 0
}

type GetAverageCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAverageCheckRequest) Reset() {
	*x = GetAverageCheckRequest{}
	mi := &file_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAverageCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAverageCheckRequest) ProtoMessage() {}

func (x *GetAverageCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAverageCheckRequest.ProtoReflect.Descriptor instead.
func (*GetAverageCheckRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{4}
}

type GetAverageCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Average       float64                `protobuf:"fixed64,1,opt,name=average,proto3" json:"average,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAverageCheckResponse) Reset() {
	*x = GetAverageCheckResponse{}
	mi := &file_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAverageCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAverageCheckResponse) ProtoMessage() {}

func (x *GetAverageCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAverageCheckResponse.ProtoReflect.Descriptor instead.
func (*GetAverageCheckResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *GetAverageCheckResponse) GetAverage() float64 {
	if x != nil {
		return x.Average
	}
	return 0
}

type RecordOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordOrderRequest) Reset() {
	*x = RecordOrderRequest{}
	mi := &file_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordOrderRequest) ProtoMessage() {}

func (x *RecordOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordOrderRequest.ProtoReflect.Descriptor instead.
func (*RecordOrderRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *RecordOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecordOrderRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *RecordOrderRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *RecordOrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *RecordOrderRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RecordOrderRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type RecordOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordOrderResponse) Reset() {
	*x = RecordOrderResponse{}
	mi := &file_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordOrderResponse) ProtoMessage() {}

func (x *RecordOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordOrderResponse.ProtoReflect.Descriptor instead.
func (*RecordOrderResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *RecordOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\x12\tanalytics\"\x13\n" +
	"\x11GetRevenueRequest\".\n" +
	"\x12GetRevenueResponse\x12\x18\n" +
	"\arevenue\x18\x01 \x01(\x01R\arevenue\"\x12\n" +
	"\x10GetOrdersRequest\"+\n" +
	"\x11GetOrdersResponse\x12\x16\n" +
	"\x06orders\x18\x01 \x01(\x05R\x06orders\"\x18\n" +
	"\x16GetAverageCheckRequest\"3\n" +
	"\x17GetAverageCheckResponse\x12\x18\n" +
	"\aaverage\x18\x01 \x01(\x01R\aaverage\"\xac\x01\n" +
	"\x12RecordOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"/\n" +
	"\x13RecordOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xcd\x02\n" +
	"\x10AnalyticsService\x12I\n" +
	"\n" +
	"GetRevenue\x12\x1c.analytics.GetRevenueRequest\x1a\x1d.analytics.GetRevenueResponse\x12F\n" +
	"\tGetOrders\x12\x1b.analytics.GetOrdersRequest\x1a\x1c.analytics.GetOrdersResponse\x12X\n" +
	"\x0fGetAverageCheck\x12!.analytics.GetAverageCheckRequest\x1a\".analytics.GetAverageCheckResponse\x12L\n" +
	"\vRecordOrder\x12\x1d.analytics.RecordOrderRequest\x1a\x1e.analytics.RecordOrderResponseB\x19Z\x17analytics/internal/grpcb\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_analytics_proto_goTypes = []any{
	(*GetRevenueRequest)(nil),       // 0: analytics.GetRevenueRequest
	(*GetRevenueResponse)(nil),      // 1: analytics.GetRevenueResponse
	(*GetOrdersRequest)(nil),        // 2: analytics.GetOrdersRequest
	(*GetOrdersResponse)(nil),       // 3: analytics.GetOrdersResponse
	(*GetAverageCheckRequest)(nil),  // 4: analytics.GetAverageCheckRequest
	(*GetAverageCheckResponse)(nil), // 5: analytics.GetAverageCheckResponse
	(*RecordOrderRequest)(nil),      // 6: analytics.RecordOrderRequest
	(*RecordOrderResponse)(nil),     // 7: analytics.RecordOrderResponse
}
var file_analytics_proto_depIdxs = []int32{
	0, // 0: analytics.AnalyticsService.GetRevenue:input_type -> analytics.GetRevenueRequest
	2, // 1: analytics.AnalyticsService.GetOrders:input_type -> analytics.GetOrdersRequest
	4, // 2: analytics.AnalyticsService.GetAverageCheck:input_type -> analytics.GetAverageCheckRequest
	6, // 3: analytics.AnalyticsService.RecordOrder:input_type -> analytics.RecordOrderRequest
	1, // 4: analytics.AnalyticsService.GetRevenue:output_type -> analytics.GetRevenueResponse
	3, // 5: analytics.AnalyticsService.GetOrders:output_type -> analytics.GetOrdersResponse
	5, // 6: analytics.AnalyticsService.GetAverageCheck:output_type -> analytics.GetAverageCheckResponse
	7, // 7: analytics.AnalyticsService.RecordOrder:output_type -> analytics.RecordOrderResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
